name: AzingoCore
version: '1.0'
main: eu.duckrealm.azingoCore.AzingoCore
api-version: '1.21'
commands:
  discord:
    description: 'Discord command'
    usage: '/discord'
    aliases: [dc]
    permission: 'azingocore.discord'
  balance:
    description: 'Balance command'
    usage: '/balance'
    aliases: [bal]
    permission: 'azingocore.balance'
  pay:
    description: 'Pay command'
    usage: '/pay <player> <amount>'
    permission: 'azingocore.pay'
