name: AzingoCore
version: '1.0'
main: eu.duckrealm.azingoCore.AzingoCore
api-version: '1.21'
commands:
  discord:
    description: 'Discord command'
    usage: '/discord'
    aliases: [dc]
    permission: 'azingocore.discord'
  balance:
    description: 'Balance command'
    usage: '/balance'
    aliases: [bal]
    permission: 'azingocore.balance'
  pay:
    description: 'Pay command'
    usage: '/pay <player> <amount>'
    permission: 'azingocore.pay'
  lock:
    description: 'Locks the server for events'
    usage: '/lock'
    permission: 'azingocore.op.lock'
  unlock:
    description: 'Unlocks the server after events'
    usage: '/unlock'
    permission: 'azingocore.op.lock'
permissions:
  azingocore.discord:
    description: 'Allows the player to use the discord command'
    default: true
  azingocore.balance:
    description: 'Allows the player to use the balance command'
    default: true
  azingocore.pay:
    description: 'Allows the player to use the pay command'
    default: true
  azingocore.op.lock:
    description: 'Allows the player to use the lock and unlock commands'
    default: op
  azingocore.op.bypasslock:
    description: 'Allows the player to bypass the lock'
    default: op